### ISSUE TITLE
[Feature Request] speed up checkout dialog

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/satspay#25]
Hi! - Satspay is one my favorite Extensions, thank you much for writing it. 

However, the number one end user complaint I get is how long it takes for the timed dialog box and QR code to load. On a fast network connection it is no problem, other times it can be very slow and delayed.

I only took a brief look at the code and i see there is a mempool.js that has to remote load, is this possible cause of the slow down? Is there some way to speed this up as an option? 

Thanks in advance. 
<img width="724" alt="Screenshot 2023-10-10 at 4 50 08 PM" src="https://github.com/lnbits/satspay/assets/73979971/6defd31a-bb18-4685-a962-8e0ac3a7d424">

**Comment by motorina0** [comment]
![image](https://github.com/lnbits/satspay/assets/2951406/97955c67-099b-423e-be18-1f22f31ec184)

- The largest downloaded file is the bundle.
- @dni can we have a sort of `bundle-light.min.js` that only includes the logic required for public pages?

**Comment by dni** [comment]
i feel like the biggest part is quasar and vue which is still needed, not quite sure if it will bring that down significantly.

but as bitkarrot suggested, i think the problem is mempool.js from a cdn, i noticed some cdns are not really reliable especially when your geolocation is very different from your lnbits server. that is what i would suggest. include it into static

**Comment by motorina0** [comment]
From the screenshot one can see that:
 - mempool.js - `2.76 s`
 - bundle.min.js - `11.49 s`

Which one should we optimize?

@bitkarrot can you please share the browser network stats on your side please

**Comment by motorina0** [comment]
On a second thought I think @dni is right. `mempool.js` should be served as an extension resource.

**Comment by talvasconcelos** [comment]
Does this mean it should go on core and be part of the bundle? 

added in lnbits/satspay#23

**Comment by bitkarrot** [comment]
@motorina0 this is what i see on a business network connection

<img width="1219" alt="Screenshot 2023-10-12 at 2 55 11 PM" src="https://github.com/lnbits/satspay/assets/73979971/cf92641a-e1d1-4d95-982a-315fba35cde6">

**Comment by dni** [comment]
`320ms` :D but mempool.js was cached

**Comment by motorina0** [comment]
Handled here: https://github.com/lnbits/satspay/pull/26
