### ISSUE TITLE
Pending balance missing in API

### ISSUE THREAD

**Issue by btcteun** [lnbits/satspay#3]
In the UI of the satspay extension it's visible when a transaction to the address is pending. 

The API however, doesn't contain this information. 
Is it possible to add at least a boolean which indicates if a balance is pending? Or perhaps even the amount that is pending?

**Comment by talvasconcelos** [comment]
The information on the UI comes from mempool... The API model doesn't have a pending field.

@motorina0 @blackcoffeexbt , is it worth adding? Implies changing models, and an extra mempool api call...

**Comment by motorina0** [comment]
The state of the charge should be exposed via the API.
If I remember correctly, the charge is updated if there is an webhook to be called. That flag could be used.
