### ISSUE TITLE
Enable to use newer version of address

### ISSUE THREAD

**Issue by afeezaziz** [lnbits/satspay#32]
At the moment, all receive addresses are using legacy address. It is quite expensive for users, appreciate it to enable to change receive address to be P2SH, P2WPKH or P2TR addresses.

**Comment by motorina0** [comment]
The Sats Pay extension depends on the Watchonly extension to generate the onchain addresses.

The type of onchain address that will be generated depends on the selected onchain wallet/account.

### Testnet Segwit:
![image](https://github.com/lnbits/satspay/assets/2951406/e74a433f-c4aa-4b75-a18b-2181a5e86d21)

### Address

![image](https://github.com/lnbits/satspay/assets/2951406/cca463fa-9e28-4c3e-897c-568d29f9144b)
