### ISSUE TITLE
Onchain payment - webhook not called if user closes browser

### ISSUE THREAD

**Issue by lnbright** [lnbits/satspay#37]
For onchain payment the customer has to keep the payment page open for 2 confirmations (unless we go for 0conf) before the webhook is called and the completelink is shown. 

Problem: if the customer broadcast the transaction but closes the page before the 2 confirmations, then the webhook to confirm receipts of funds is not called and the completelink is not shown. 

Is there a way around this? Can the wehbook be called on the background after 2 confirmations are detected even if the customer closes the browser?

**Comment by bitkarrot** [comment]
Further note: 
Webhooks not called after payment is made on lightning, for versions 0.11.3 -> 0.12 as of dev branch Jan 25, 2024
Webhook is called after payment for version 0.10.9

Some divergence here but have not had the time to pinpoint it. 
@dni

**Comment by dni** [comment]
merged https://github.com/lnbits/satspay/pull/46
