### ISSUE TITLE
webhook issue

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/satspay#6]
When both onchain and lnbits wallet are enabled for SatsPay, with any webhook, 

For some reason when loading the satspay QR Code page, the presence of the webhook url shows that the invoice is already paid, when it hasn't been paid! Also the data sent to the webhook is instant, and it shows the invoice is paid, even though it is not. It is as if the wait time is bypassed for paying the invoice and just set to "paid" status as default.

Very odd why this is the case. However, once the webhook variable value is blank, '' the invoice shows normally. 

```
body = {
        "onchainwallet": ONCHAIN_WALLET,
        "lnbitswallet": LNBITS_WALLET,
        "description": desc,
        "webhook": webhook,
        "completelink": "",
        "completelinktext": "",
        "custom_css": "",
        "time": 1440,
        "amount": sats_amount,
        "extra": "{\"mempool_endpoint\": \"https://mempool.space\", \"network\": \"Mainnet\"}"
    }
```

**Comment by motorina0** [comment]
> When both onchain and lnbits wallet are enabled f

Is it possible that your `Onchain` address already has the expected amount therefore it is considered paid?

If you have both `onchain` and `lnbits` only one of them has to be paid in order to call the webhook.

**Comment by bitkarrot** [comment]
I tested this with an empty onchain wallet with webhook

If there is only `lnbits` wallet, the webhook is not automatically called until the payment is made

If I add the onchain address, the QR page says its already paid.

**Comment by talvasconcelos** [comment]
Can't reproduce this issue. 

Tried creating a new charge, onchain and ln, webhook only triggered when payment was set!

**Comment by bitkarrot** [comment]
I updated to LNbits version: 0.10.9, Commit version: docker
Satspay extension 0.2.3

Just tried it again with a new regular wallet and a regular admin wallet.
Regular wallet worked first try with a new OnChain Wallet entry.

Admin wallet, the existing on chain wallet kept triggering the checkmark before payment. 
Had to reset the onchain wallet, by deleting the entry in OnChain Wallet Extension and then recreating, with the same exact zpub and then sats pay extension with on chain payment and webhook worked. 

Unclear if was address related or something else in the On Chain Wallet Extension that was causing the skip and not displaying QR code on Sats Pay

**Comment by bitkarrot** [comment]
Ah Just now discovered this - 
I went and Rescanned all the wallets in the OnChain Wallet Extensions and that solved the checkmark problem!

Might be a good idea to make it clear somewhere on both the Tip Extension and SatsPay extension to have onchain wallet scanned to prevent issues like the QR code skip.

**Comment by talvasconcelos** [comment]
Can I close the issue?

**Comment by bitkarrot** [comment]
yes. closing issue. Thanks @talvasconcelos
